#!/usr/bin/env python3
"""Temporary script to analyze prompts using cursor-agent."""

import json
import subprocess
import sys
from pathlib import Path

# Read the prompt from stdin or use the provided one
prompt_text = sys.stdin.read() if not sys.stdin.isatty() else ""

if not prompt_text:
    # Use the provided prompt
    prompt_text = """Analyze these prompts from a coding session and identify patterns that would benefit from Cursor rules or commands.

These prompts are from the project: unknown

Prompt 1 (2026-01-05T22:13:23.566Z):
 I'd like to change the check against existing rules and commands to use the cursor-cli, similar to what we do for actually creating new rules. Help me plan this out, and minimize cli runs. Ideally the flow should be:
1. Use the filesystem to gather existing rules and commands
2. Include these in the prompt to the cursor-agent and let it know these rules are already in place and should get ignored
3. Cursor-agent generates net new recommendations

Prompt 2 (2026-01-05T21:29:45.676Z):
cursor-agent -p is the syntax

Prompt 3 (2026-01-05T21:29:20.302Z):
You already fetch for local rules

Prompt 4 (2026-01-05T21:28:26.696Z):
> I'd like to change the check against existing rules and commands to use the cursor-cli, similar to what we do for actually creating new rules. Help me plan this out, and minimize cli runs

Prompt 5 (2026-01-05T18:40:44.227Z):
@zsh 

Prompt 6 (2026-01-05T18:32:43.293Z):
make sure the rules and commands are also scanned for in ~/.cursor/.... aka the user's root dir

Prompt 7 (2026-01-05T18:04:16.465Z):
Let's make some stylistic improvements to the html report generated by recommend:
1. Include a tab view to split rules vs commands
2. Include a log view of all the prompts considered as a separate tab
3. Use deeplinks (https://cursor.com/docs/integrations/deeplinks#deeplinks ) to easily make the commands addable to cursor

We also need to factor in the existing commands and rules someone already has defined. Consult:
https://cursor.com/docs/context/rules 
https://cursor.com/docs/agent/chat/comma

Prompt 8 (2026-01-05T17:58:22.933Z):
test this out in the terminal

Prompt 9 (2026-01-05T17:57:03.971Z):
how can I easily test this? I have been tracking prompts locally using it already

Prompt 10 (2026-01-05T17:53:44.755Z):
We should also pass the "-m composer-1" to the cursor cli

Prompt 11 (2026-01-05T17:52:22.314Z):
Instead of having these predefined patterns, we should be using the cursor cli to come up with rules and commands. Otherwise we'll be limited in the types of patterns we can look for.

Prompt 12 (2026-01-05T17:50:25.466Z):
workspace_roots

Prompt 13 (2026-01-05T17:47:23.018Z):
Let's add a new cli command to propose cursor commands and rules based on recent prompts. These will need to be project aware, since commands and rules can be set at the project level or the global level.

They should propose either type (user aka global or project) depending on whether the patterns are used across multiple projects. Ideally they should be able to output these recommendations as an html page with copy-pasteable commands and rules.

The job of creating the commands and rules shou

Prompt 14 (2026-01-05T17:38:59.062Z):
We need to filter out certain pre-saved prompts from the analysis:
1. "Issue reproduced, please proceed."
2. "The issue has been fixed. Please clean up the instrumentation."
3. "Implement the plan as specified, it is attached for your reference. Do NOT edit the plan file itself.

To-do's from the plan have already been created. Do not create them again. Mark them as in_progress as you work, starting with the first one. Don't stop until you have completed all the to-dos."

We should also filter o

Prompt 15 (2026-01-05T17:35:54.743Z):
create a plan for a my day view

Prompt 16 (2026-01-05T17:32:57.759Z):
/run-preflight-nextjs-checks 

Prompt 17 (2026-01-05T16:55:45.331Z):
okay this seems to be working, but it only holds until I refresh the page

Prompt 18 (2026-01-05T16:54:25.107Z):
move my recent 3 commits to main to a new branch

Prompt 19 (2026-01-05T16:27:30.602Z):
We're seeing an issue where when you try to assign an event to a trial, the UI does not update, and it's unclear whether the underlying database updates.

 DOM Path: div.group/.idebar-wrapper ha.-data-[variant=in.et]:bg-card min-h-.creen w-full [&_[data-.lot=.idebar-container]]:top-14 [&_[data-.lot=.idebar-container]]:h-[calc(100.vh-3.5rem)] flex flex-col h-.creen overflow-hidden > div.flex-1 flex min-w-0 overflow-hidden > main.bg-background relative flex w-full flex-1 flex-col md:peer-data-[var

Prompt 20 (2026-01-05T15:52:17.387Z):
I want to add a new observability option similar to otel. How would I start doing that here

Prompt 21 (2026-01-05T15:49:20.467Z):
/create-docs 

Prompt 22 (2026-01-05T15:43:26.220Z):
We're seeing an issue with our Cash holdings. Any time we add one then it gets duplicated

Prompt 23 (2026-01-05T15:30:38.599Z):
Update the jira ticket status and infomratino showing this is complete

Prompt 24 (2026-01-05T15:23:13.039Z):
Read ticket KAN-90 from atlassian jira, then analyze our codebase and build a plan for how we can implement this ticket

Prompt 25 (2026-01-05T15:18:07.656Z):
Talk me through how this project i sstructured, and create a single md file with mermaid diagrams on how it works

Prompt 26 (2026-01-05T14:44:52.966Z):
still not working. I'm testing with an unassigned event

Prompt 27 (2026-01-05T14:43:45.535Z):
it's still not working

Prompt 28 (2026-01-05T14:39:50.205Z):
Okay now this seems to have broken assigning that event to a trial

Prompt 29 (2026-01-05T14:37:19.723Z):
Error didn't appear this time, but the change didn't take and the event is still assigned

Prompt 30 (2026-01-05T14:36:06.431Z):
Unassign gives an error

Prompt 31 (2026-01-05T14:35:22.559Z):
## Error Type
Build Error

## Error Message
Parsing ecmascript source code failed

## Build Output
./apps/trial-tracker/src/components/dashboard/my-week-view.tsx:807:39
Parsing ecmascript source code failed
  805 |                       : (selectedEventTrials[matchingEventId || reassigningEventId || ""] === null 
  806 |                           ? "Unassign" 
> 807 |                           : "Attach")))}
      |                                       ^
  808 |               </Button>
  809 | 

Prompt 32 (2026-01-05T14:34:33.183Z):
allow for this to be set to unassigned

Prompt 33 (2026-01-05T14:33:26.858Z):
Add an option to the my week page to reassign which trial an event is attached to

Prompt 34 (2026-01-05T14:31:45.122Z):
redirected to a failed state "Error Loading Events" page

Prompt 35 (2026-01-05T14:31:02.202Z):
I'm immediately getting a react error after 2

Prompt 36 (2026-01-05T14:29:37.354Z):
We're seeing an issue when trying to attach an event to a trial, e.g. via: DOM Path: div.group/.idebar-wrapper ha.-data-[variant=in.et]:bg-card min-h-.creen w-full [&_[data-.lot=.idebar-container]]:top-14 [&_[data-.lot=.idebar-container]]:h-[calc(100.vh-3.5rem)] flex flex-col h-.creen overflow-hidden > div.flex-1 flex min-w-0 overflow-hidden > main.bg-background relative flex w-full flex-1 flex-col md:peer-data-[variant=in.et]:m-2 md:peer-data-[variant=in.et]:ml-0 md:peer-data-[variant=in.et]:ro

Prompt 37 (2026-01-05T14:27:25.281Z):
Can we force a rerun of the matching logic? I'm still seeing mismatches but I think those are being stored

Prompt 38 (2026-01-05T14:24:06.753Z):
Build a plan to remove the aspect of fuzzy matching entirely. We should instead just be using direct matches for the email domains in cal events to the domains in account and or opp records. We should still ignore the internal email domains

Prompt 39 (2026-01-05T14:20:35.602Z):
how do we do the event matching for calendar events in the trial tracker to trials? We're seeing this cause issues where clearly incorrect matches are made

Prompt 40 (2026-01-05T13:50:02.194Z):
Give me 5 more that include some sort of visual update that shows a new feature

Prompt 41 (2026-01-05T13:48:08.919Z):
/create-demo-tickets create them in jira

Prompt 42 (2026-01-05T13:45:56.027Z):
talk me through this project, and build a single md file with mermaid docs showing how it works

Prompt 43 (2026-01-02T18:10:15.877Z):
The asset allocation pie chart gets really screwed up and overlapping. Can we address this? We can just remove the labels on the chart and rely on the legend?

Prompt 44 (2026-01-02T18:03:36.599Z):
Execute this plan

Prompt 45 (2026-01-02T18:03:29.949Z):
Execute this plan

Prompt 46 (2026-01-02T17:58:52.966Z):
Let's update the styling of our @JS+TS/portfolio-management-dashboard/ :
1. Let's move to a menubar and tabbed view for Portfolio Overview, Allocations, Holdings, and Transcations
2. Change to a black white and red theme
3. Aim for a more modern, professional, layout and styling

Prompt 47 (2026-01-02T17:51:16.154Z):
Plan it out

Prompt 48 (2026-01-02T17:50:51.061Z):
It looks like we're missing a way to define our portfolio outside of public investments. Is that correct?

Prompt 49 (2026-01-02T17:45:52.872Z):
Let's add some other features to this @JS+TS/portfolio-management-dashboard/  dashboard to make it more realistic. Start with a new section for defining our allocation between public investments, cash, bonds, private investments, etc. We should have public sources for these, so change the cateogries to fit that. Aim for realism

Prompt 50 (2026-01-02T17:43:50.219Z):
create a new branch and commit our changes

... and 631 more prompts

EXISTING RULES AND COMMANDS (DO NOT DUPLICATE):
The following rules and commands already exist. Do not recommend anything that duplicates or closely matches these:

EXISTING COMMANDS:
  - customer-response (User Global)
    Content preview: # customer-response

Make the response customer-facing, and less than one paragraph. Do not reference specific lines of code, however you can reference high level pieces of architecture that are gener...
  - log-status (User Global)
    Content preview: I need to pick this up tomorrow, write a summary of what we've done in this current chat along with the current state of things, and the next step. Just print it here, do not create a doc.
  - generate-trial-usage-report (User Global)
    Content preview: Generate an html report of trial metrics based on the attached file.

Generate a python file to create this report.

The report should consider the full date range represented in the linked file, and ...
  - deslop (User Global)
    Content preview: # Remove AI code slop

Check the diff against main, and remove all AI generated slop introduced in this branch.

This includes:
- Extra comments that a human wouldn't add or is inconsistent with the r...
  - create-docs (User Global)
    Content preview: # create-docs

Talk me through this project, and build a single md file with mermaid diagrams showing how it works. Verify your mermaid docs to make sure the formatting is correct.

  - clear-processes (User Global)
    Content preview: Kill any running Node, Python, Java, or other dev servers on common ports like 8000, 8001, 3000, 3001, 3002, 5173, 5174, etc.
  - commit (User Global)
    Content preview: Commit the changes from this agent chat to git. Do not include any changes beyond this chat.
  - create-demo-tickets (User Global)
    Content preview: Create a new project in Linear. Then create 5 tickets within that project. Each ticket should be either a new feature or a technical enhancement we can make to this repository. Each ticket should just...


For each pattern you identify, provide:
1. Type: Either "Rule" (for persistent guidance/instructions) or "Command" (for actions to invoke)
2. Name: A descriptive name for the rule/command
3. Content: The complete rule or command content in proper format
4. Reasoning: Why this pattern warrants automation

Format your response as JSON with this structure:
{
  "recommendations": [
    {
      "type": "Rule" or "Command",
      "name": "descriptive name",
      "content": "full rule/command content",
      "reasoning": "explanation"
    }
  ]
}

Focus on patterns that:
- Are repeated frequently
- Represent coding style preferences
- Define workflows that could be automated
- Capture domain-specific conventions
- Would benefit from being persistent or reusable

Return only valid JSON, no additional text before or after."""

try:
    result = subprocess.run(
        ["cursor-agent", "--model", "composer-1", "--print", "--output-format", "json", prompt_text],
        capture_output=True,
        text=True,
        timeout=120,
    )
    
    if result.returncode != 0:
        print(f"Error: cursor-agent failed with return code {result.returncode}", file=sys.stderr)
        print(f"stderr: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    
    output = result.stdout.strip()
    
    # Try to parse JSON
    try:
        wrapper = json.loads(output)
        if isinstance(wrapper, dict) and "result" in wrapper:
            result_text = wrapper["result"]
            json_start = result_text.find('{')
            json_end = result_text.rfind('}') + 1
            if json_start >= 0 and json_end > json_start:
                json_str = result_text[json_start:json_end]
                parsed = json.loads(json_str)
            else:
                parsed = json.loads(result_text)
        else:
            parsed = wrapper
        
        print(json.dumps(parsed, indent=2))
    except json.JSONDecodeError as e:
        json_start = output.find('{')
        json_end = output.rfind('}') + 1
        if json_start >= 0 and json_end > json_start:
            json_str = output[json_start:json_end]
            parsed = json.loads(json_str)
            print(json.dumps(parsed, indent=2))
        else:
            print(f"Error parsing JSON: {e}", file=sys.stderr)
            print(f"Output: {output[:500]}", file=sys.stderr)
            sys.exit(1)
except FileNotFoundError:
    print("Error: cursor-agent not found. Make sure Cursor CLI is installed.", file=sys.stderr)
    sys.exit(1)
except Exception as e:
    print(f"Error calling cursor-agent: {e}", file=sys.stderr)
    sys.exit(1)
